export enum ItemActionType {
	ITEM_CHANGE_STRING = "ITEM_CHANGE_STRING",
	ITEM_CHANGE_NUMBER = "ITEM_CHANGE_NUMBER",
	ITEM_CHANGE_BOOLEAN = "ITEM_CHANGE_BOOLEAN",
	ITEM_CREATE_ELEMENTT = "ITEM_CREATE_ELEMENTT",
	ITEM_UPDATE_ELEMENTT = "ITEM_UPDATE_ELEMENTT",
	ITEM_DELETE_ELEMENTT = "ITEM_DELETE_ELEMENTT",
}

export enum ItemzActionType {
	ITEM_FETCH = "ITEM_FETCH",
	ITEM_CREATE = "ITEM_CREATE",
	ITEM_UPDATE = "ITEM_UPDATE",
	ITEM_DELETE = "ITEM_DELETE",
}

export enum RecordActionType {
	RECORD_FETCH = "RECORD_FETCH",
	RECORD_CREATE = "RECORD_CREATE",
	RECORD_UPDATE = "RECORD_UPDATE",
	RECORD_DELETE = "RECORD_DELETE",
}
